# Generated by Django 3.0.8 on 2020-07-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='staticfiles/assets/images/'),
        ),
    ]
